Prepare virtual channels
hyperledger-labs/perun-eth-contracts pull request #10
Opened 2021-05-21 09:05 UTC by matthiasgeihs

Closes #9

2021-06-07 17:01 UTC, sebastianst requested changes
An intro meeting would be good as there are quite some substantial changes. But generally looks very good.

We also need to hash in the `bool ledgerChannel` for the `channelId` calculation, or users can just set it as they want, no?

2021-06-23 04:52 UTC, matthiasgeihs commented on contracts/Channel.sol
> +        bool virtualChannel;
I agree, it's not super clean right now and using Enums might be better if we keep that distinction.

However, it should be possible to go back to only a single flag `ledgerChannel` once we implement the protocols for virtual channels with sub-channels in go-perun, so I prefer to keep as is for now.

2021-06-23 05:08 UTC, matthiasgeihs commented
> Please open an issue regarding virtual sub-app-channels, which we should add at some point.

Done, #12

2021-06-23 10:12 UTC, sebastianst commented on contracts/Channel.sol
> +        bool virtualChannel;
OK let's do it in #12 if we realize we need it.

2021-06-23 10:18 UTC, sebastianst approved these changes
LGTM

2021-06-23 12:31 UTC, merged