[README] Replace outdated wiki link with link to perun-docs.
hyperledger-labs/perun-eth-contracts pull request #20
Opened 2021-11-05 13:03 UTC by matthiasgeihs

The wiki that is linked to is out-dated and only exists in the archived perun-network repository. This change replaces that link with a link to the perun-doc page.

2021-11-05 13:43 UTC, ggwpez commented
The *go-perun* in the title of the `README` does not point to the HLL repo.  
@matthiasgeihs

2021-11-05 15:14 UTC, sebastianst requested changes
See Oli's comment

2021-11-09 13:02 UTC, ggwpez approved these changes

2021-11-09 13:08 UTC, sebastianst approved these changes

2021-11-09 13:09 UTC, merged